version: '3.1'
services:
  stats-server:
    build: ./stats
    container_name: explore-with-me-stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore_with_me_stats
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: explore-with-me-stats-postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore_with_me_stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
